# pickem
# Choosing Python 2.7 for AWS Lambda use
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python -m unittest fetcher.tests.test_fetch_functions
